export const PLACE_NEW_ORDER_REQUEST = "PLACE_NEW_ORDER_REQUEST";
export const PLACE_NEW_ORDER_SUCCESS = "PLACE_NEW_ORDER_SUCCESS";
export const PLACE_NEW_ORDER_FAIL = "PLACE_NEW_ORDER_FAIL";
export const PLACE_NEW_ORDER_RESET = "PLACE_NEW_ORDER_RESET";
