export const PLACE_NEW_ORDER_REQUEST = "PLACE_NEW_ORDER_REQUEST";
export const PLACE_NEW_ORDER_SUCCESS = "PLACE_NEW_ORDER_SUCCESS";
export const PLACE_NEW_ORDER_FAIL = "PLACE_NEW_ORDER_FAIL";
export const PLACE_NEW_ORDER_RESET = "PLACE_NEW_ORDER_RESET";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";
