export const PLACE_NEW_ORDER_REQUEST = "PLACE_NEW_ORDER_REQUEST";
export const PLACE_NEW_ORDER_SUCCESS = "PLACE_NEW_ORDER_SUCCESS";
export const PLACE_NEW_ORDER_FAIL = "PLACE_NEW_ORDER_FAIL";
export const PLACE_NEW_ORDER_RESET = "PLACE_NEW_ORDER_RESET";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const UPDATE_DELIVERY_REQUEST = "UPDATE_DELIVERY_REQUEST";
export const UPDATE_DELIVERY_SUCCESS = "UPDATE_DELIVERY_SUCCESS";
export const UPDATE_DELIVERY_FAIL = "UPDATE_DELIVERY_FAIL";
export const UPDATE_DELIVERY_RESET = "UPDATE_DELIVERY_RESET";

export const USER_ORDERS_LIST_REQUEST = "USER_ORDERS_LIST_REQUEST";
export const USER_ORDERS_LIST_SUCCESS = "USER_ORDERS_LIST_SUCCESS";
export const USER_ORDERS_LIST_FAIL = "USER_ORDERS_LIST_SUCCESS";

export const ALL_ORDERS_LIST_REQUEST = "ALL_ORDERS_LIST_REQUEST";
export const ALL_ORDERS_LIST_SUCCESS = "ALL_ORDERS_LIST_SUCCESS";
export const ALL_ORDERS_LIST_FAIL = "ALL_ORDERS_LIST_FAIL";
